### ISSUE TITLE
report rebate function in the club class

### ISSUE THREAD

**Issue by ywang208** [ywang208/cs-8-first-project#10]
A report that prints out the rebate of all the preferred members sorted by membership number.

**Comment by gnrmdz** [comment]
as a user i want to calculate 5% rebate savings for all preferred members so that i can print out results in GUI

medium priority

testing:
function must handle case when there are no preferred members/empty class


Def of Done:
- accurately prints out all rebate savings for preferred member
- functional with Graphical interface
- sorted by membership number

**Comment by ywang208** [comment]
as a club owner, I want to print all the debate information so that I can know want happened before
