### ISSUE TITLE
report per year paid function in club

### ISSUE THREAD

**Issue by ywang208** [ywang208/cs-8-first-project#11]
A report showing the amount per year paid by each member for the membership dues sorted by member type (basic/preferred and then by member name.)

**Comment by gnrmdz** [comment]
as a developer i want to print out all money paid by members so that user can view it in GUI

Medium priority

Testing:
Function will be tested to handle empty class
tested to see if sorting is correct

Def. of Done:
- sorts all members by member type then by member name
- prints out member type, member name, and money spent per year

**Comment by ywang208** [comment]
As a club owner, I want to know  per year paid by each member for the membership, to know how much is the price, and how many people change the membership type before.
