### ISSUE TITLE
know memberships expire function in club

### ISSUE THREAD

**Issue by ywang208** [ywang208/cs-8-first-project#12]
A user should be able to enter a month and get a list of all members whose memberships expire that month as well as their dues amount.

**Comment by gnrmdz** [comment]
As a developer i want to open file to check which members membership expires on any given month, so that a list of members can be printed to GUI

Medium Priority

Testing:
Will test all possible month configurations
will test incorrect month input

Def. of Done
- Prints out all members whose membership expires on given month
- fully functional with GUI
-

**Comment by ywang208** [comment]
as club owner, I want get the information about how many members will expire in an exact month, to manage the manage the members.
