### ISSUE TITLE
if preferred is better function in member class

### ISSUE THREAD

**Issue by ywang208** [ywang208/cs-8-first-project#13]
Determine if any basic customer should convert their membership to preferred status.

**Comment by gnrmdz** [comment]
As a member, I want to be able to see if 5% savings is greater than extra money spent on preferred membership price so that i can know whether to switch memberships

This function takes total money spent by member and checks to see if 5% of that is greater than difference in price between basic and preferred. 

low priority

testing:

Def of done:
function is done when it properly returns bool indicating whether preferred membership is more cost-effective for a particular member

**Comment by ywang208** [comment]
as a normal member, I want to have a function to get the information if I should be a preferred member, because I want to save money
