### ISSUE TITLE
graphic

### ISSUE THREAD

**Issue by ywang208** [ywang208/cs-8-first-project#15]
graphic user interface

**Comment by gnrmdz** [comment]
As a user, I want to be able to navigate program using a graphical interface so that I can use program outside of terminal window.

QT GUI provides a visual interface for user to access member functions.

Low Priority

Testing:
All member functions will be tested individually to match what program does.

Def. of Done
GUI is done when all member functions for classes can be accessed and provide the correct response/do the correct action
All information is neatly displayed for user in an intuitive way.
