### ISSUE TITLE
function to input and output information from right file 

### ISSUE THREAD

**Issue by ywang208** [ywang208/cs-8-first-project#3]
A sales report for any given day. It should include a list of items and quantities sold on that day as well names of the members who shopped that day.  Report the total revenue for the given day.  It should also include number of preferred members and basic members who shopped during the given day.

**Comment by gnrmdz** [comment]
As a developer, I want to read and write information dealing with the member/item data, so that I can save and access it through multiple executions of the program.

This function opens the file holding information from previous executions of the program in order to continue where it left off.

Low priority

Testing:
Function will be tested by running program multiple times to save and reaccess data stored in .txt file

Def. of Done
Function is done when used can close program and reopen it without losing data.

**Comment by ywang208** [comment]
as user, i want to save the change every time in the file, and read it when open the program, because I need to use the right information after the file changes every time .
