### ISSUE TITLE
Agile Story #4 (Member Class Code)

### ISSUE THREAD

**Issue by ghost** [ywang208/cs-8-first-project#31]
---
# Agile Story #4 (Member Class Code)
---

## WHAT NEEDS TO BE DONE (User Story):
**`“As a programmer, I want to build a member class so that we can store data into the variables needed. First, in order to build a member class are to determine whether each member of the Wholesale Club are either the preferred and basic members. Preferred members are the ones who are like business owners to buy what they need in order to make their business to keep on running while the basic members are the ones who are like shoppers who buys like groceries and other stuff to support their families. The variables that are needed for the member class are the name, identification number, membership expiration date, membership type (preferred or basic members), and total amount spent for all the members of the Wholesale Club. You are to write a program that services members of Wholesale Club. You must use a container class with at least one overloaded operator. You should also describe the growth rate of your program. At least one class must contain a pointer (a copy constructor needs to be written an You are to write a program that services members of Wholesale Club. You must use a container class with at least one overloaded operator. You should also describe the growth rate of your program. At least one class must contain a pointer (a copy constructor needs to be written an You are to write a program that services members of Wholesale Club. You must use a container class with at least one overloaded operator. You should also describe the growth rate of your program. At least one class must contain a pointer (a copy constructor needs to be written an You are to write a program that services members of Wholesale Club. You must use a container class with at least one overloaded operator. You should also describe the growth rate of your program. At least one class must contain a pointer."`**

---
> - Story Point Estimation: 20
> - Story Point Priority: High-High
> - Assignee: @ywang208 & @phildkim86
> - Task 1: ~~Adding new member or members:.~~
> - Task 2: ~~Delete member.~~
> - Task 3: ~~Create a class to display reports.~~
> - Task 4: ~~Get the information about one member.~~
> - Task 5: ~~Get information about all members.~~
> - Task 6: ~~Get rebate.~~
> - Task 7: ~~Report the members when user input an expire month.~~
> - Task 8: ~~Report the total spend.~~
> - Task 9: ~~The payment about the membership.~~
> - Task 10: ~~Report the members when user input an expire month.~~
> - Task 11: ~~Determine if the preferred member or the basic member should change the member type.~~
> - Task 12: ~~Figure out which member that the user want to choose, when user input name or id.~~
---

---
> ### For adding or generate a new member, there should be three parameters, name, id and member type. For import the member information form the file, it will take all date about the name, id and member type, but for generating a new member, it will generate a number about the id, and this id should not exist in the list.
```c++
void MembersList::addMember(string name, bool prefered, int id, string date)
```
---

---
> ### For changing the spend, there should be several parameters, item price, amount, customer id. Use the price and the amount to get the spend, and then update the value of the customer with the specific id..
```c++
void MembersList::changeSpend(double spend, int id)
```
---

---
> ### In this part it will return a string variable when user input a user id. If the customer is exist, return the information about the customer, else return a error message. The customer information will include the user name, id, member type, and the register date.

```c++
string MembersList::getMemberInfo(int id)
string MembersList::getMemberInfoFromPos(int pos)
```
---

---
> ### For get the information from all members, it will use loop to go through all members in the list and call getMemberInfoFromPos(pos);, to get the string value about the member information. What is more all information will sort by the id. To make the list sort by the id, there should be a function to sort the list, it will call the function in the algorithm in the library to sort.

```c++
string MembersList::getMemberInfo(int id)
```
---

---
> ### This function will return a string value include the information about the rebate from all preferred member, and it will sort by id. In this function, there is only preferred member in the return value.

```c++
string MembersList::reportRebate()
```
---

---
> ### In this function, when user input a number of the month(that means the parameter is a int which present the month), it will return a string value which include all members who will be expired in the month. And it will sort by id.

```c++
string MembersList::reportExpire(int month)
string MembersList::getAllInfo()
```
---

---
> ### In this function, the main purpose is to show the spend from each member. So it will return a string value include information about spend from all members, and every line will have the id, name, and the spend form the customer. Additional, it will sort by id..

```c++
string MembersList::reportTotalSpend()
```
---

---
> ### This function will return a string value about the payment for every member. Each line will include the name, id, member type and the membership fee. Basic will come first and then is the preferred, and it also sort by name.

```c++
string MembersList::reportPayMembership()
```
---

---
> ### Determine if the preferred member or the basic member should change the member type
In this function, it will take the id as a parameter, and then get the member type, next compare the rebate to the difference form the two types membership fee. For the type is preferred, if the rebate is greater than 15, return true, else return false; for the basic, assume there is a rebate, if it is greater than 15, return false, else return true.

```c++
bool MembersList::shouldBePreferred(int id)
bool MembersList::shouldBeBasic(int id)
```
---

---
> ### Figure out which member that the user want to choose, when user input name or id.
When user input some thing that we do not know if it is a id or if it is a name, it is difficult to find the specific member in the list because the types of the id and name are different( int and string). So to figure out the problem, the first thing is uniting the type of the id and name to string, and then get the user input as a string. By this method, program can check if the input is a part of the name or id. If it is in the id and name string, it will return the id, else return -1(there is no any id is negative )..

```c++
string MembersList::idAndName(Member m)
```
---

### Definition of Done 
- [x] ~~Code produced that adheres to a coding standard Code commented~~
- [x] ~~Code checked into source control system~~
- [x] ~~Peer reviewed (or produced with pair programming) Unit tests written and passed~~
- [x] ~~Relevant documentation/diagrams produced and/or updated Product owner concurs~~
> Peer reviewed by: @ywang208 & @dthai5 

> ### Developer said,
`"This class is a little bit complex. Therefore, to test this class, we need to separate it to two step.
For the first step, we can only use a member information file and write a easy main function to check the functions which is not about the purchase.
And then, after finish the purchase class, we can check the rest.."`

**Comment by ywang208** [comment]
Story Point Estimation: 20;
Story Priority: high
Assignee: @ywang208 
List of task: short list

As a programmer, I want to build a member class so that we can store data into the variables needed. First, in order to build a member class are to determine whether each member of the Wholesale Club are either the preferred and basic members. Preferred members are the ones who are like business owners to buy what they need in order to make their business to keep on running while the basic members are the ones who are like shoppers who buys like groceries and other stuff to support their families. The variables that are needed for the member class are the name, identification number, membership expiration date, membership type (preferred or basic members), and total amount spent for all the members of the Wholesale Club. You are to write a program that services members of Wholesale Club. You must use a container class with at least one overloaded operator. You should also describe the growth rate of your program. At least one class must contain a pointer (a copy constructor needs to be written an You are to write a program that services members of Wholesale Club. You must use a container class with at least one overloaded operator. You should also describe the growth rate of your program. At least one class must contain a pointer (a copy constructor needs to be written an You are to write a program that services members of Wholesale Club. You must use a container class with at least one overloaded operator. You should also describe the growth rate of your program. At least one class must contain a pointer (a copy constructor needs to be written an You are to write a program that services members of Wholesale Club. You must use a container class with at least one overloaded operator. You should also describe the growth rate of your program. At least one class must contain a pointer

For this part, there are 11 very important parts:
1.adding new member or members: 
For adding or generate a new member, there should be three parameters, name, id and member type. For import the member information form the file, it will take all date about the name, id and member type, but for generating a new member, it will generate a number about the id, and this id should not exist in the list. 
```c++
  void MembersList::addMember(string name, bool prefered, int id, string date)
{
    // randome new id for the new member
    if (id == -1){
        srand(time(NULL));
        do{
            id = rand() % 1000000 + 1;
        }while(idExist(id));
    }
    mlyst.push_back(Member(name, id, prefered, date));
}
```
2.delete member:
For deleting a member, the id is the most important stuff. After put the id as a parameter, user can check where is the element and then find where the element is in the list. Finally, use "erase" function for the vector, to delete that element:
```c++
void MembersList::deleteMember(int id, string name)
{
    mlyst.erase(mlyst.begin() + getPos(id, name));
}
```
3.change the spend of the member when  add new purchase:
For changing the spend, there should be several parameters, item price, amount, customer id. Use the price and the amount to get the spend, and then update the value of the customer with the specific id.
```c++
void MembersList::changeSpend(double spend, int id)
{
    int pos = getPos(id);
    mlyst[pos].spend += spend;
    if(mlyst[pos].prefered)
        mlyst[pos].rebate += rebateRate * spend;
}
```  
4.get the information about one member
In this part it will return a string variable when user input a user id. If the customer is exist, return the information about the customer, else return a error message. The customer information will include the user name, id, member type, and the register date.
```c++
string MembersList::getMemberInfo(int id)
{
    int pos = getPos(id);
    string result = getMemberInfoFromPos(pos);
    return result;
}
string MembersList::getMemberInfoFromPos(int pos)
{
    string result = "";
    result += mlyst[pos].memberName + "\n" + to_string(mlyst[pos].memberId) + "\n";
    // type
    result += mlyst[pos].prefered? "Preferred\n": "Basic\n";
    // date
    result += mlyst[pos].date.printDate();
    return result;
}
```
5.get information about all members
For get the information from all members, it will use loop to go through all members in the list and call getMemberInfoFromPos(pos);, to get the string value about the member information. What is more all information will sort by the id. To make the list sort by the id, there should be  a function to sort the list, it will call the function in the algrithem in the library to sort.
```c++
string MembersList::getAllInfo()
{
    sortById();
    string result = "";
    for(int i = 0; i < size(); ++i)
    {
        // member name and the id
        result += mlyst[i].memberName + "\n" + to_string(mlyst[i].memberId)
                + "\n";
        // the type of the member
        result += mlyst[i].prefered? "Preferred\n": "Basic\n";
        // date
        result += mlyst[i].date.printDate();

        if(i < size() - 1)
            result += "\n";
    }
    return result;
}
void MembersList::sortById()
{
    struct SortPart
    {
        bool operator()(Member f, Member s){return (f.memberId < s.memberId);}
    }idSort;
    sort(mlyst.begin(), mlyst.end(), idSort);
}
```
6.report the rebate
This function will return a string value include the information about the rebate from all preferred member, and it will sort by id. In this function, there is only preferred member in the return value.
```c++
string MembersList::reportRebate()
{
    string result = "";
    sortById();
    for(int i = 0; i < size(); ++i)
    {
        if(mlyst[i].prefered)
            result += infoType(mlyst[i], 30, 12) +
                    to_string(mlyst[i].rebate) + "\n";
    }
    return result;
}
```
7.report the members when user input an expire month
In this function, when user input a number of the month(that means the parameter is a int which present the month), it will return a string value which include all members who will be expired in the month. And it will sort by id.
```c++
string MembersList::reportExpire(int month)
{
    string result = "";
    sortById();
    for(int i = 0; i < size(); ++i)
    {
        if(mlyst[i].date.getMonth() == month)
            result += getMemberInfo(mlyst[i].memberId) + "\n";
    }
    return result;
}
```
8.report the total spend 
In this function, the main propuse is to show the spend from each member. So it will return a string value include information about spend from all members, and every line will have the id, name, and the spend form the customer. Additional, it will sort by id.
```c++
string MembersList::reportTotalSpend()
{
    stringstream ss;
    string temp;
    string result = "";
    for(int i = 0; i < size(); ++i)
    {
        ss << mlyst[i].spend;
        ss>> temp;
        ss.clear();
        result += infoType(mlyst[i], 50, 25) + temp+"\n";
    }
    return result;
}
```
9.the payment about the membership
This function will return a string value about the payment for every member. Each line will include the name, id, member type and the membership fee. Basic will come first and then is the preferred, and it also sort by name.
```c++
string MembersList::reportPayMembership()
{
    string resultBasic = "";
    string resultPrefered = "";
    sortByName();
    for(int i = 0; i < size(); ++i)
    {
        // for the preferred
        if(mlyst[i].prefered)
            resultPrefered += infoType(mlyst[i], 50, 25) + to_string(preferedFee) + "\n";
        // for the basic
        else
            resultBasic += infoType(mlyst[i], 50, 25) + to_string(basicFee) + "\n";
    }
    return resultBasic + resultPrefered;
}
```

10.determine if the preferred member or the basic member should change the member type
In this function, it will take the id as a parameter, and then get the member type, next compare the rebate  to the difference form the two types membership fee. For the type is preferred, if the rebate is greater than 15, return true, else return false; for the basic, assume there is a rebate, if it is greater than 15, return false, else return true.
```c++ 
bool MembersList::shouldBePreferred(int id)
{
    int pos = 0;
    for(; pos < size(); ++pos)
    {
        if(id == mlyst[pos].memberId)
            break;
    }
    if((mlyst[pos].spend * rebateRate) < (preferedFee - basicFee))
        return false;
    return true;
}
bool MembersList::shouldBeBasic(int id)
{
    int pos = 0;
    for(; pos < size(); ++pos)
    {
        if(id == mlyst[pos].memberId)
            break;
    }
    if(mlyst[pos].spend * rebateRate >= preferedFee - basicFee)
        return false;
    return true;
}
```
11.figure out which member that the user want to choose, when user input name or id.
When user input some thing that we do not know if it is a id or if it is a name, it is difficult to find the specific member in the list because the types of the id and name  are different( int and string). So to figure out the problem, the first thing is uniting the type of the id and name to string, and then get the user input as a string. By this method, program can check if the input is a part of the name or id. If it is in the id and name string, it will return the id, else return -1(there is no any id is negative ).
```c++
string MembersList::idAndName(Member m)
{
    string result = to_string(m.memberId) + "\t" + m.memberName;
    return result;
}
```

Developer Said:
This class is a little bit complex. Therefore, to test this class, we need to separate it to two step.
For the first step, we can only use a member information file and write a easy main function to check the functions which is not about the purchase.
And then, after finish the purchase class, we can check the rest.
