### ISSUE TITLE
show total purchases function in club class

### ISSUE THREAD

**Issue by ywang208** [ywang208/cs-8-first-project#6]
A report that prints the total purchases by all the members sorted by membership number.  It should also include a grand total of the purchases.

**Comment by gnrmdz** [comment]
As a user i want to be able to sort all purchases by membership number so that I can print them in GUI with the total amount of money

Medium Priority

testing:
tested with multiple executions of program to ensure consistency in sort
testing to ensure grand total is accurate

Def of Done
This function is done when all purchases are printed, sorted by membership number
Grand total is printed after all purchases

**Comment by ywang208** [comment]
as a club owner, I want to print all the members purchase so that I can know what happen to my members.
