### ISSUE TITLE
report the quantity are sold in storage class

### ISSUE THREAD

**Issue by ywang208** [ywang208/cs-8-first-project#9]
A report that prints out the quantity of each item sold sorted by item name.

**Comment by ywang208** [comment]
include which items and how many are sold

**Comment by gnrmdz** [comment]
As a developer i want to access file to read all purchases of each item so that i can print out a report detailing each purchase sorted by item name.

Low Priority

Testing:
Different executions will be tested with different lists of purchases

Def of Done:
- all items are printed
- sorted by item name
